# Generated by Django 3.0.6 on 2020-05-18 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articulos',
            fields=[
                ('id_articulos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='personas',
            fields=[
                ('id_personas', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tpo_articulo',
            fields=[
                ('id_tpo_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='precios',
            fields=[
                ('id_precios', models.AutoField(primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('tipo_lista', models.CharField(default='minorista', max_length=9)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.articulos')),
            ],
        ),
        migrations.AddField(
            model_name='articulos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.tpo_articulo'),
        ),
    ]
